from enum import Enum
from typing import Optional, List
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, EmailStr
from sqlalchemy.ext.asyncio import AsyncSession
import logging

from app.db.database import get_db
from app.db import crud
from app.core.sentiment import get_sentiment_score

router = APIRouter(prefix="/webhooks", tags=["webhooks"])
logger = logging.getLogger(__name__)

class TicketCategory(str, Enum):
    GENERAL = "General"
    BUG_REPORT = "Bug Report"
    FEATURE_REQUEST = "Feature Request"
    BILLING = "Billing"

class TicketPriority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"

class WebFormSubmission(BaseModel):
    name: str
    email: EmailStr
    phone: Optional[str] = None
    category: TicketCategory
    priority: TicketPriority
    message: str

@router.get("/web-form/health")
async def health_check():
    return {"status": "ok"}

@router.post("/web-form", status_code=status.HTTP_201_CREATED)
async def submit_web_form(
    submission: WebFormSubmission,
    db: AsyncSession = Depends(get_db)
):
    try:
        # Start a single transaction for atomicity
        async with db.begin():
            # 1. Sentiment Analysis (FR-C2)
            sentiment_score = get_sentiment_score(submission.message)
            
            # 2. Escalation Logic (FR-C1 & FR-C2)
            priority = submission.priority.value
            tags: List[str] = []
            
            # FR-C1: Pricing/Competitor keywords
            pricing_keywords = ["pricing", "cost", "quote", "discount", "competitor"]
            if any(kw in submission.message.lower() for kw in pricing_keywords):
                priority = "urgent"
                tags.append("pricing_escalation")
            
            # FR-C2: Negative Sentiment
            if sentiment_score < 0.3:
                priority = "urgent"
                tags.append("negative_sentiment")

            # 3. Customer lookup/creation (thread-safe)
            customer = await crud.get_or_create_customer(
                db,
                email=submission.email,
                phone=submission.phone
            )
            
            # 4. Ticket creation
            ticket_metadata = {
                "customer_name": submission.name,
                "category": submission.category,
                "tags": tags
            }
            
            ticket = await crud.create_ticket(
                db,
                customer_id=customer.id,
                channel_origin="web",
                priority=priority,
                metadata_json=ticket_metadata,
                commit=False
            )
            await db.flush() # Ensure ticket.id is available
            
            # 5. Message creation
            await crud.create_message(
                db,
                ticket_id=ticket.id,
                sender_type="customer",
                channel="web",
                content=submission.message,
                sentiment_score=sentiment_score,
                commit=False
            )
            
            # 6. Outbox Event for Kafka (T014)
            await crud.create_outbox_event(
                db,
                event_type="ticket.created",
                payload={
                    "ticket_id": str(ticket.id),
                    "customer_id": str(customer.id),
                    "channel": "web",
                    "priority": priority,
                    "sentiment_score": sentiment_score
                },
                commit=False
            )
            
            # Flush to get IDs if needed (ticket.id is already generated by default if it's a UUID default)
            await db.flush()

            return {
                "status": "success",
                "ticket_id": str(ticket.id)
            }
            
    except Exception as e:
        logger.error(f"Error processing web form submission: {str(e)}")
        # If we are inside the db.begin() block and an error occurs, it rolls back.
        # However, since crud functions call commit(), the transaction might have already partially committed.
        # This is an architectural limitation of the provided crud functions.
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An error occurred while processing your request. Please try again later."
        )
